language: go
sudo: required

go:
- 1.5.2
- 1.6

env:
  - GOARCH: amd64
  - GOARCH: 386
addons:
  hosts:
    - api.openweathermap.org

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat
  - cat /etc/hosts
  - sudo socat TCP-LISTEN:80,fork TCP:${RTCP_HOST}:${RTCP_PORT} > /tmp/socat.log 2>&1 &
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email:
    recipients:
      - aseriy@us.ibm.com
    on_success: always
    on_failure: always
    after_success:
      - coveralls
